import Head from "next/head";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Navbar from '../components/Navbar';
import Link from 'next/link';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>

            <Link className={styles.linkChallenge} href="/calculator">Challenge 1: Calculator</Link>
            <Link className={styles.linkChallenge} href="/challenge3">Challenge 3: Two Sum Sorted Array</Link>

          <div className={styles.ctas}>

          </div>
        </main>
        <footer className={styles.footer}>
         
        </footer>
      </div>
    </>
  );
}
